export const GET_PRACTICE_TOPICS_LOADING = "GET_PRACTICE_TOPICS_LOADING"
export const GET_PRACTICE_TOPICS_SUCCESS = "GET_PRACTICE_TOPICS_SUCCESS";
export const GET_PRACTICE_TOPICS_FAILURE = "GET_PRACTICE_TOPICS_FAILURE";