export const GET_PRACTICE_TOPICS_LOADING = "GET_PRACTICE_TOPICS_LOADING"
export const GET_PRACTICE_TOPICS_SUCCESS = "GET_PRACTICE_TOPICS_SUCCESS";
export const GET_PRACTICE_TOPICS_FAILURE = "GET_PRACTICE_TOPICS_FAILURE";

// start practice
export const START_PRACTICE_LOADING = "START_PRACTICE_LOADING"
export const START_PRACTICE_SUCCESS = "START_PRACTICE_SUCCESS";
export const START_PRACTICE_FAILURE = "START_PRACTICE_FAILURE";