export const GET_PRACTICE_TOPICS_LOADING = "GET_PRACTICE_TOPICS_LOADING";
export const GET_PRACTICE_TOPICS_SUCCESS = "GET_PRACTICE_TOPICS_SUCCESS";
export const GET_PRACTICE_TOPICS_FAILURE = "GET_PRACTICE_TOPICS_FAILURE";

// start practice
export const START_PRACTICE_LOADING = "START_PRACTICE_LOADING";
export const START_PRACTICE_SUCCESS = "START_PRACTICE_SUCCESS";
export const START_PRACTICE_FAILURE = "START_PRACTICE_FAILURE";

//get next question

export const GET_NEXT_QUESTION_LOADING = "GET_NEXT_QUESTION_LOADING";
export const GET_NEXT_QUESTION_SUCCESS = "GET_NEXT_QUESTION_SUCCESS";
export const GET_NEXT_QUESTION_FAILURE = "GET_NEXT_QUESTION_FAILURE";

// bookmarks

export const POST_BOOKMARK_LOADING = "POST_BOOKMARK_LOADING";
export const POST_BOOKMARK_SUCCESS = "POST_BOOKMARK_SUCCESS";
export const POST_BOOKMARK_FAILURE = "POST_BOOKMARK_FAILURE";

//likes

export const POST_LIKE_LOADING = "POST_LIKE_LOADING";
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS";
export const POST_LIKE_FAILURE = "POST_LIKE_FAILURE";

// Send Question report
export const POST_REPORT_LOADING = "POST_REPORT_LOADING";
export const POST_REPORT_SUCCESS = "POST_REPORT_SUCCESS";
export const POST_REPORT_FAILURE = "POST_REPORT_FAILURE";
