const storageEnums = Object.freeze({
    QUESTION_PRACTICE: 'QUESTION_PRACTICE',
    PRACTICE_RESULTS: 'PRACTICE_RESULTS',
    ATTEMPT_ID: 'ATTEMPT_ID',
    SUBMISSION_ID: 'SUBMISSION_ID',
    ALL_QUESTIONS: 'ALL_QUESTIONS',
    TOKEN : 'TOKEN',
    NAME : 'NAME',
    EMAIL : 'EMAIL',
    PROFILEPIC : 'PROFILEPIC',
})

export { storageEnums }