const storageEnums = Object.freeze({
  QUESTION_PRACTICE: "QUESTION_PRACTICE",
  LONG_QUESTION_PRACTICE: "LONG_QUESTION_PRACTICE",
  LONG_QUESTION_IDs: "LONG_QUESTION_IDs",
  PRACTICE_RESULTS: "PRACTICE_RESULTS",
  ATTEMPT_ID: "ATTEMPT_ID",
  SUBMISSION_ID: "SUBMISSION_ID",
  ALL_QUESTIONS_IDS: "ALL_QUESTIONS_IDS",
  TOKEN: "TOKEN",
  NAME: "NAME",
  EMAIL: "EMAIL",
  PROFILEPIC: "PROFILEPIC",
  TOPIC: "TOPIC",
  USER_ID: "USER_ID",
  RECOVERY_EMAIL: "RECOVERY_EMAIL",
  SIGN_UP_EMAIL: "SIGN_UP_EMAIL",
  TEMP_PASS: "TEMP_PASS",
  LONG_TYPE_NAV_TOPIC: "LONG_TYPE_NAV_TOPIC",
});

export { storageEnums };
