const adminConstants = {
    GET_ALL_QUESTIONS_LOADING: "GET_ALL_QUESTIONS_LOADING",
    GET_ALL_QUESTIONS_SUCCESS: "GET_ALL_QUESTIONS_SUCCESS",
    GET_ALL_QUESTIONS_FAILURE: "GET_ALL_QUESTIONS_FAILURE",
    GET_QUESTIONS_BY_TOPIC_LOADING: "GET_QUESTIONS_BY_TOPIC_LOADING",
    GET_QUESTIONS_BY_TOPIC_SUCCESS: "GET_QUESTIONS_BY_TOPIC_SUCCESS",
    GET_QUESTIONS_BY_TOPIC_FAILURE: "GET_QUESTIONS_BY_TOPIC_FAILURE",
    GET_TOPICS_LOADING: "GET_TOPICS_LOADING",
    GET_TOPICS_SUCCESS: "GET_TOPICS_SUCCESS",
    GET_TOPICS_FAILURE: "GET_TOPICS_FAILURE",
    DELETE_QUESTION_LOADING: "DELETE_QUESTION_LOADING",
    DELETE_QUESTION_SUCCESS: "DELETE_QUESTION_SUCCESS",
    DELETE_QUESTION_FAILURE: "DELETE_QUESTION_FAILURE",
    ADD_QUESTION_LOADING: "ADD_QUESTION_LOADING",
    ADD_QUESTION_SUCCESS: "ADD_QUESTION_SUCCESS",
    ADD_QUESTION_FAILURE: "ADD_QUESTION_FAILURE",
    EDIT_QUESTION_LOADING: "EDIT_QUESTION_LOADING",
    EDIT_QUESTION_SUCCESS: "EDIT_QUESTION_SUCCESS",
    EDIT_QUESTION_FAILURE: "EDIT_QUESTION_FAILURE",
  };
  
  export { adminConstants };