const adminConstants = {
    GET_CRUD_TOPICS_REQUEST: "GET_CRUD_TOPICS_REQUEST",
    GET_CRUD_TOPICS_SUCCESS: "GET_CRUD_TOPICS_SUCCESS",
    GET_CRUD_TOPICS_FAILURE: "GET_CRUD_TOPICS_FAILURE",
    POST_CRUD_TOPIC_REQUEST: "POST_CRUD_TOPIC_REQUEST",
    POST_CRUD_TOPIC_SUCCESS: "POST_CRUD_TOPIC_SUCCESS",
    POST_CRUD_TOPIC_FAILURE: "POST_CRUD_TOPIC_FAILURE",
    GET_BY_CRUD_TOPIC_ID_REQUEST: "GET_BY_CRUD_TOPIC_ID_REQUEST",
    GET_BY_CRUD_TOPIC_ID_SUCCESS: "GET_BY_CRUD_TOPIC_ID_SUCCESS",
    GET_BY_CRUD_TOPIC_ID_FAILURE: "GET_BY_CRUD_TOPIC_ID_FAILURE",
    DELETE_CRUD_TOPIC_REQUEST: "DELETE_CRUD_TOPIC_REQUEST",
    DELETE_CRUD_TOPIC_SUCCESS: "DELETE_CRUD_TOPIC_SUCCESS",
    DELETE_CRUD_TOPIC_FAILURE: "DELETE_CRUD_TOPIC_FAILURE",
    PUT_CRUD_TOPIC_REQUEST: "PUT_CRUD_TOPIC_REQUEST",
    PUT_CRUD_TOPIC_SUCCESS: "PUT_CRUD_TOPIC_SUCCESS",
    PUT_CRUD_TOPIC_FAILURE: "PUT_CRUD_TOPIC_FAILURE",
}

export { adminConstants };