export const GET_BOOKMARKS_COUNT_LOADING = "GET_BOOKMARKS_COUNT_LOADING";
export const GET_BOOKMARKS_COUNT_SUCCESS = "GET_BOOKMARKS_COUNT_SUCCESS";
export const GET_BOOKMARKS_COUNT_FAILURE = "GET_BOOKMARKS_COUNT_FAILURE";

export const GET_TOPICWISE_BOOKMARKS_LOADING =
  "GET_TOPICWISE_BOOKMARKS_LOADING";
export const GET_TOPICWISE_BOOKMARKS_SUCCESS =
  "GET_TOPICWISE_BOOKMARKS_SUCCESS";
export const GET_TOPICWISE_BOOKMARKS_FAILURE =
  "GET_TOPICWISE_BOOKMARKS_FAILURE";
