const authConstants = {
  USERS_SIGNUP_REQUEST: "USERS_SIGNUP_REQUEST",
  USERS_SIGNUP_SUCCESS: "USERS_SIGNUP_SUCCESS",
  USERS_SIGNUP_FAILURE: "USERS_SIGNUP_FAILURE",

  USERS_VERIFICATION_REQUEST: "USERS_VERIFICATION_REQUEST",
  USERS_VERIFICATION_SUCCESS: "USERS_VERIFICATION_SUCCESS",
  USERS_VERIFICATION_FAILURE: "USERS_VERIFICATION_FAILURE",

  USERS_SIGNIN_REQUEST: "USERS_SIGNIN_REQUEST",
  USERS_SIGNIN_SUCCESS: "USERS_SIGNIN_SUCCESS",
  USERS_SIGNIN_FAILURE: "USERS_SIGNIN_FAILURE",

  RESEND_OTP_REQUEST: "RESEND_OTP_REQUEST",
  RESEND_OTP_SUCCESS: "RESEND_OTP_SUCCESS",
  RESEND_OTP_FAILURE: "RESEND_OTP_FAILURE",
};

export { authConstants };
