const authConstants = {
    USERS_SIGNUP_REQUEST: "USERS_SIGNUP_REQUEST",
    USERS_SIGNUP_SUCCESS: "USERS_SIGNUP_SUCCESS",
    USERS_SIGNUP_FAILURE: "USERS_SIGNUP_FAILURE",

    USERS_VERIFICATION_REQUEST: "USERS_VERIFICATION_REQUEST",
    USERS_VERIFICATION_SUCCESS: "USERS_VERIFICATION_SUCCESS",
    USERS_VERIFICATION_FAILURE: "USERS_VERIFICATION_FAILURE",

  }
  
  export { authConstants }
  