import { makeStyles } from "@material-ui/core/styles";

const modalStyles = makeStyles((theme) => ({
  flex: {
    display: "flex",
    justifyContent: "space-around",
    width: "788px",
    padding: "12px 12px 12px 16px",
    "& div": {
      height: "40px",
      background: "rgba(108, 141, 158, 0.1)",
      borderRadius: "4px",
      alignItems: "center",
      padding: "9px",
      cursor: "pointer",
      fontFamily: "DM Sans",
      fontSize: "16px",
      letterSpacing: "0.4px",
      color: "#4E565A",
    },
  },
  title: {
    fontFamily: "Open Sans",
    fontStyle: "normal",
    fontSize: "14px",
    fontWeight: "bold",
    color: "#111B20",
    margin: "19px",
    marginTop: "14px",
    lineHeight: "170%",
    height: "24px",
    width: "381px",
    letterSpacing: "0.5px",
    marginLeft: "21px",
  },
  textAreaWidth: {
    width: "97%",
    marginLeft: 13,

    height: "133px",
    background: "rgba(108, 141, 158, 0.1)",
    borderRadius: "4px",
  },
  buttonFlex: {
    display: "flex",
    marginLeft: "600px",
    "& button": {
      width: "115px",
      height: "48px",
      boxShadow: "0px 6px 12px rgba(0, 0, 0, 0.16)",
      borderRadius: "8px",
      border: 0,
      fontSize: "18px",
      textAlign: "center",
      margin: "25px 10px",
      fontStyle: "DM Sans",
    },
  },
  submit: {
    color: "white",
  },
  details: {
    height: "24px",
    lineHeight: "150%",
    letterSpacing: "0.2px",
    fontWeight: "bold",
    fontSize: "15px",
  },
  hr: {
    height: "1px",
    width: "100%",
    background: "D6D6D6",
  },
  report: {
    color: "#6C8D9E",
    fontFamily: "Open Sans",
    fontSize: "18px",
    margin: "5px 0px 15px 18px",
    lineHeight: "24px",
    textDecorationLine: "underline",
    paddingBottom: "20px",
    cursor: "pointer",
  },
  sourceURL: {
    color: "#6C8D9E",
    fontFamily: "Open Sans",
    fontSize: "18px",
    margin: "5px 0px -8px 0px",
    lineHeight: "24px",
    textDecorationLine: "underline",
    paddingBottom: "20px",
    cursor: "pointer",
  },
  modalWidth: {
    width: "500px",
    height: "650px",
    marginLeft: "38%",
  },
  issue: {
    fontFamily: "Open Sans",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: 14,
    lineHeight: "170%",
    /* identical to box height, or 24px */

    color: "#333434",
  },
  // submitBtn: {
  //   width: 280,
  //   height: 56,
  //   background: "linear-gradient(239.11deg, #1E90FF -4.11%, #2B75CD 88.83%)",
  //   boxShadow: "0px 12px 16px -10px rgba(30, 144, 255, 0.6)",
  //   borderRadius: 8,
  //   color: "#FFFFFF",
  //   marginRight: "17%",
  // },
}));

export { modalStyles };
