const questionConstant = {
    GET_QUESTIONS_LOADING: "GET_QUESTIONS_LOADING",
    GET_QUESTIONS_SUCCESS: "GET_QUESTIONS_SUCCESS",
    GET_QUESTIONS_FAILURE: "GET_QUESTIONS_FAILURE",
  };
  
  export { questionConstant };