
export const GET_QUESTION_LOADING = 'GET_QUESTION_LOADING'
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS'
export const GET_QUESTION_FAILURE = 'GET_QUESTION_FAILURE'

export const RECORD_ANSWER_LOADING = 'RECORD_ANSWER_LOADING'
export const RECORD_ANSWER_SUCCESS = 'RECORD_ANSWER_SUCCESS'
export const RECORD_ANSWER_FAILURE = 'RECORD_ANSWER_FAILURE'

export const ATTEMPT_QUIZ_LOADING = 'ATTEMPT_QUIZ_LOADING'
export const ATTEMPT_QUIZ_SUCCESS = 'ATTEMPT_QUIZ_SUCCESS'
export const ATTEMPT_QUIZ_FAILURE = 'ATTEMPT_QUIZ_FAILURE'