const questionConstant = {
    GET_NEXT_QUESTION_LOADING: 'GET_NEXT_QUESTION_LOADING',
    GET_NEXT_QUESTION_SUCCESS: 'GET_NEXT_QUESTION_SUCCESS',
    GET_NEXT_QUESTION_FAILURE: 'GET_NEXT_QUESTION_FAILURE'
}

const answerConstant = {
    RECORD_ANSWER_SUCCESS: 'RECORD_ANSWER_SUCCESS',
    RECORD_ANSWER_FAILURE: 'RECORD_ANSWER_FAILURE'
}

export {questionConstant, answerConstant}