const topicConstant = {
  GET_TOPICS_LOADING: "GET_TOPICS_LOADING",
  GET_TOPICS_SUCCESS: "GET_TOPICS_SUCCESS",
  GET_TOPICS_FAILURE: "GET_TOPICS_FAILURE",
};

const questionsConstants = {
 ATTEMPT_QUIZ_LOADING: 'ATTEMPT_QUIZ_LOADING',   
 ATTEMPT_QUIZ_SUCCESS: 'ATTEMPT_QUIZ_SUCCESS',   
 ATTEMPT_QUIZ_FAILURE: 'ATTEMPT_QUIZ_FAILURE'   
}

export { topicConstant, questionsConstants };
  