export const GET_TOPICS_LOADING = "GET_TOPICS_LOADING"
export const GET_TOPICS_SUCCESS = "GET_TOPICS_SUCCESS"
export const GET_TOPICS_FAILURE = "GET_TOPICS_FAILURE"

export const ATTEMPT_QUIZ_LOADING = 'ATTEMPT_QUIZ_LOADING'
export const ATTEMPT_QUIZ_SUCCESS = 'ATTEMPT_QUIZ_SUCCESS'
export const ATTEMPT_QUIZ_FAILURE = 'ATTEMPT_QUIZ_FAILURE'