const authConstants = {
  USERS_LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  USERS_LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  USERS_LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
}

export { authConstants }
