export const GET_PREVIOUS_ATTEMPTS_REQUEST = "GET_PREVIOUS_ATTEMPTS_REQUEST";
export const GET_PREVIOUS_ATTEMPTS_SUCCESS = "GET_PREVIOUS_ATTEMPTS_SUCCESS";
export const GET_PREVIOUS_ATTEMPTS_FAILURE = "GET_PREVIOUS_ATTEMPTS_FAILURE";
