export const GET_RESULT_LOADING = "GET_RESULT_LOADING";
export const GET_RESULT_SUCCESS = "GET_RESULT_SUCCESS";
export const GET_RESULT_FAILURE = "GET_RESULT_FAILURE";

export const GET_REPORT_LOADING = "GET_REPORT_LOADING";
export const GET_REPORT_SUCCESS = "GET_REPORT_SUCCESS";
export const GET_REPORT_FAILURE = "GET_REPORT_FAILURE";
