export const GET_RESULT_LOADING = "GET_RESULT_LOADING";
export const GET_RESULT_SUCCESS = "GET_RESULT_SUCCESS";
export const GET_RESULT_FAILURE = "GET_RESULT_FAILURE";

export const SEND_REPORT_LOADING = "SEND_REPORT_LOADING";
export const SEND_REPORT_SUCCESS = "SEND_REPORT_SUCCESS";
export const SEND_REPORT_FAILURE = "SEND_REPORT_FAILURE";
